CREATE TABLE `Admins` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pw` VARCHAR(100) NOT NULL,
  `last_login` DATETIME DEFAULT NULL,
  `token` VARCHAR(100) NOT NULL,
  `token_expr` DATETIME NOT NULL,
  PRIMARY KEY (`id`,`email`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `Links` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `admin_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `URL` VARCHAR(2083) NOT NULL,
  PRIMARY KEY (`id`,`admin_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `Referrals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NOT NULL,
  `admin_id` INT(11) NOT NULL,
  `referral` VARCHAR(45) NOT NULL,
  `ref_expr` DATETIME NOT NULL,
  PRIMARY KEY (`id`,`admin_id`, `client_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `Clicks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NOT NULL,
  `click_date` DATETIME NOT NULL,
  `click_loc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`,`client_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `Clients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `admin_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) DEFAULT NULL,
  `joined` DATETIME NOT NULL,
  PRIMARY KEY (`id`,`admin_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


